version: '3.8'

services:

  backend:
    build: 
      context: ./payment-routing-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ibm-mq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payments
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - IBM_MQ_HOST=ibm-mq
      - IBM_MQ_PORT=1414
    networks:
      - app-network


  frontend:
    build: 
      context: ./payment-routing-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network


  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app-network


  ibm-mq:
    image: ibmcom/mq
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    volumes:
      - ibm-mq-data:/mnt/mqm
    networks:
      - app-network

volumes:
  postgres-data:
  ibm-mq-data:

networks:
  app-network:
    driver: bridge